<a href="https://colab.research.google.com/github/khairillkmn/newdataset/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['India' 34.0 92000.0]
 ['Sri lanka' 22.0 25000.0]
 ['China' 31.0 74000.0]
 ['Sri lanka' 29.0 nan]
 ['China' 55.0 98000.0]
 ['India' 24.0 30000.0]
 ['Sri lanka' 28.0 40000.0]
 ['India' nan 60000.0]
 ['China' 51.0 89000.0]
 ['India' 44.0 78000.0]
 ['Sri lanka' 21.0 20000.0]
 ['China' 25.0 30000.0]
 ['India' 33.0 45000.0]
 ['India' 42.0 65000.0]
 ['Sri lanka' 33.0 22000.0]]


In [4]:
print(y)

['Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'No']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['India' 34.0 92000.0]
 ['Sri lanka' 22.0 25000.0]
 ['China' 31.0 74000.0]
 ['Sri lanka' 29.0 54857.142857142855]
 ['China' 55.0 98000.0]
 ['India' 24.0 30000.0]
 ['Sri lanka' 28.0 40000.0]
 ['India' 33.714285714285715 60000.0]
 ['China' 51.0 89000.0]
 ['India' 44.0 78000.0]
 ['Sri lanka' 21.0 20000.0]
 ['China' 25.0 30000.0]
 ['India' 33.0 45000.0]
 ['India' 42.0 65000.0]
 ['Sri lanka' 33.0 22000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[0.0 1.0 0.0 34.0 92000.0]
 [0.0 0.0 1.0 22.0 25000.0]
 [1.0 0.0 0.0 31.0 74000.0]
 [0.0 0.0 1.0 29.0 54857.142857142855]
 [1.0 0.0 0.0 55.0 98000.0]
 [0.0 1.0 0.0 24.0 30000.0]
 [0.0 0.0 1.0 28.0 40000.0]
 [0.0 1.0 0.0 33.714285714285715 60000.0]
 [1.0 0.0 0.0 51.0 89000.0]
 [0.0 1.0 0.0 44.0 78000.0]
 [0.0 0.0 1.0 21.0 20000.0]
 [1.0 0.0 0.0 25.0 30000.0]
 [0.0 1.0 0.0 33.0 45000.0]
 [0.0 1.0 0.0 42.0 65000.0]
 [0.0 0.0 1.0 33.0 22000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[1 1 1 0 1 0 0 0 1 1 0 1 1 1 0]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [13]:
print(x_train)

[[1.0 0.0 0.0 31.0 74000.0]
 [0.0 0.0 1.0 21.0 20000.0]
 [1.0 0.0 0.0 55.0 98000.0]
 [0.0 0.0 1.0 22.0 25000.0]
 [0.0 1.0 0.0 42.0 65000.0]
 [0.0 1.0 0.0 34.0 92000.0]
 [0.0 0.0 1.0 33.0 22000.0]
 [0.0 1.0 0.0 44.0 78000.0]
 [1.0 0.0 0.0 51.0 89000.0]
 [0.0 1.0 0.0 33.0 45000.0]
 [1.0 0.0 0.0 25.0 30000.0]
 [0.0 1.0 0.0 24.0 30000.0]]


In [14]:
print(x_test)

[[0.0 0.0 1.0 29.0 54857.142857142855]
 [0.0 1.0 0.0 33.714285714285715 60000.0]
 [0.0 0.0 1.0 28.0 40000.0]]


In [15]:
print(y_train)

[1 0 1 1 1 1 0 1 1 1 1 0]


In [16]:
print(y_test)

[0 0 0]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[1.0 0.0 0.0 -0.3323561357816283 0.637555294512461]
 [0.0 0.0 1.0 -1.2598616309861719 -1.2403348456878782]
 [1.0 0.0 0.0 1.8936570527092762 1.4721731346015006]
 [0.0 0.0 1.0 -1.1671110814657175 -1.0664561290026617]
 [0.0 1.0 0.0 0.6878999089433696 0.3245736044790711]
 [0.0 1.0 0.0 -0.054104487220265264 1.2635186745792406]
 [0.0 0.0 1.0 -0.14685503674071962 -1.1707833590137917]
 [0.0 1.0 0.0 0.8734010079842783 0.7766582678606342]
 [1.0 0.0 0.0 1.5226548546274588 1.1591914445681106]
 [0.0 1.0 0.0 -0.14685503674071962 -0.3709412622617953]
 [1.0 0.0 0.0 -0.8888594329043545 -0.892577412317445]
 [0.0 1.0 0.0 -0.9816099824248089 -0.892577412317445]]


In [19]:
print(x_test)

[[0.0 0.0 1.0 -0.5178572348225371 -0.02815179222522553]
 [0.0 1.0 0.0 -0.08060464422610927 0.15069488779385445]
 [0.0 0.0 1.0 -0.6106077843429915 -0.544819978947012]]
